application: dessertalbum
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
  expiration: "30d"
  
- url: /templates/(.*).js
  static_files: templates/\1.js
  upload: /templates/(.*).js
  expiration: "30d"

- url: /templates/(.*)/lng/(.*)
  static_files: templates/\1/lng/\2
  upload: templates/(.*)/lng/(.*)
  expiration: "30d"
  
- url: /templates/(.*)/css/(.*)
  static_files: templates/\1/css/\2
  upload: templates/(.*)/css/(.*)
  expiration: "30d"

- url: /templates/(.*)/images/(.*)
  static_files: templates/\1/images/\2
  upload: templates/(.*)/images/(.*)
  expiration: "30d"

- url: .*
  script: main.py